version: '2'
services:
    mysql:
        container_name: clotter_mysql
        image: mysql/mysql-server:5.7
        volumes:
          - "./mysql:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"
        command: [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--lower_case_table_names=1",
        "--sql_mode=TRADITIONAL",
        "--explicit_defaults_for_timestamp=ON"
        ]
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1